env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  {
    "react/jsx-filename-extension":
      [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
    "react/react-in-jsx-scope": 0,
    "no-use-before-define": 0,
    "react/function-component-definition": 0,
    "react/no-unescaped-entities": 0,
    "import/extensions": 0,
  }
ignorePatterns:
  - "dist/**/*"
  - "node_modules/**/*"
settings:
  {
    "import/extensions": [".js", ".jsx", ".ts", ".tsx"],
    "import/parsers": { "@typescript-eslint/parser": [".ts", ".tsx"] },
    "import/resolver":
      {
        "typescript": {},
        "node": { "extensions": [".js", ".jsx", ".ts", ".tsx"] },
      },
  }
